### ISSUE TITLE
Add get user location & sort the data from the nearest location

### ISSUE THREAD

**Issue by agallio** [agallio/ina-covid-bed#3]
## Description

Get user location from the browser, and then calculate the distance from the user's location to every available hospital.

## Implementation Model

I think it's more easy to implement at the list page first, and then after that we can replicate the behavior to the map page. We can use `haversine` formula to calculate the distance.

```js
function deg2rad(deg: number) {
  return deg * (Math.PI / 180);
}

export function getDistanceFromLatLonInKm(lat1: number, lon1: number, lat2: number, lon2: number) {
  const R = 6371; // Radius of the earth in km
  const dLat = deg2rad(lat2 - lat1); // deg2rad below
  const dLon = deg2rad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const d = R * c; // Distance in km
  return d.toFixed(2);
}
```

## Tasks

- [x] Add button to get current location
- [x] Clicking the button will get the nearest province
- [x] Redirect to `/[province]` page with geo info
- [x] Update data to sort by geo info if any

**Comment by pveyes** [comment]
can I tackle this. I have some ideas

 - add button to get current location
 - clicking the button will get nearest province
 - it will redirect to `[province]` page with geo info
 - update data to sort by geo info if any

**Comment by agallio** [comment]
Yes ofc! That would be great. I'll modify the tasks list and assign this to you @pveyes. Many thanks! 🙇🏻
